{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-mutator.fullname" . }}-config
data:
  config.json: |
    {
      "features": {{ toPrettyJson .Values.config.features | nindent 8 }},
      "maps": {{ toPrettyJson .Values.config.maps | nindent 8 }},
      "secrets": {{ toPrettyJson .Values.config.secrets | nindent 8 }}
    }
{{- end }}